(define (problem pb1) (:domain dungeon)
(:objects
    player - hero
    m0 m1 m2 m3 m4 m5 m6 - monster
    t0 t1 t2 t3 t4 t5 - trap
    s0 s1 s2 s3 - sword
    r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 r13 r14 r15 r16 r17 r18 r19 - room
)

(:init
    (hero-alive player)
    (hero-in-room player r0)
    (hero-empty-handed player)
    
    (monster-in-room m0 r2)
    (not (monster-afraid player m0))
    (monster-in-room m1 r2)
    (not (monster-afraid player m1))
    (monster-in-room m2 r9)
    (not (monster-afraid player m2))
    (monster-in-room m3 r10)
    (not (monster-afraid player m3))
    (monster-in-room m4 r12)
    (not (monster-afraid player m4))
    (monster-in-room m5 r14)
    (not (monster-afraid player m5))
    (monster-in-room m6 r15)
    (not (monster-afraid player m6))

    (trap-in-room t0 r3)
    (trap-armed t0 r3)
    (not (trap-disarmed t0 r3))
    (trap-in-room t1 r7)
    (trap-armed t1 r7)
    (not (trap-disarmed t1 r7))
    (trap-in-room t2 r8)
    (trap-armed t2 r8)
    (not (trap-disarmed t2 r8))
    (trap-in-room t3 r13)
    (trap-armed t3 r13)
    (not (trap-disarmed t3 r13))
    (trap-in-room t4 r17)
    (trap-armed t4 r17)
    (not (trap-disarmed t4 r17))
    (trap-in-room t5 r18)
    (trap-armed t5 r18)
    (not (trap-disarmed t5 r18))

    (sword-in-room s0 r5)
    (not (sword-destroyed s0))
    (not (sword-holding player s0))
    (sword-in-room s0 r6)
    (not (sword-destroyed s0))
    (not (sword-holding player s0))
    (sword-in-room s0 r11)
    (not (sword-destroyed s0))
    (not (sword-holding player s0))
    (sword-in-room s0 r16)
    (not (sword-destroyed s0))
    (not (sword-holding player s0))

    (not (room-destroyed r0))
    (not (room-destroyed r1))
    (not (room-destroyed r2))
    (not (room-destroyed r3))
    (not (room-destroyed r4))
    (not (room-destroyed r5))
    (not (room-destroyed r6))
    (not (room-destroyed r7))
    (not (room-destroyed r8))
    (not (room-destroyed r9))
    (not (room-destroyed r10))
    (not (room-destroyed r11))
    (not (room-destroyed r12))
    (not (room-destroyed r13))
    (not (room-destroyed r14))
    (not (room-destroyed r15))
    (not (room-destroyed r16))
    (not (room-destroyed r17))
    (not (room-destroyed r18))
    (not (room-destroyed r19))

    (room-cleared player r0)
    (room-cleared player r1)

    (room-corridor r0 r1)
    (room-corridor r0 r2)
    (room-corridor r1 r0)
    (room-corridor r1 r3)
    (room-corridor r1 r4)
    (room-corridor r2 r0)
    (room-corridor r2 r4)
    (room-corridor r2 r5)
    (room-corridor r3 r1)
    (room-corridor r3 r6)
    (room-corridor r3 r7)
    (room-corridor r4 r1)
    (room-corridor r4 r6)
    (room-corridor r4 r7)
    (room-corridor r4 r8)
    (room-corridor r5 r2)
    (room-corridor r5 r9)
    (room-corridor r5 r8)
    (room-corridor r6 r3)
    (room-corridor r6 r10)
    (room-corridor r7 r3)
    (room-corridor r7 r4)
    (room-corridor r7 r10)
    (room-corridor r7 r11)
    (room-corridor r8 r4)
    (room-corridor r8 r5)
    (room-corridor r8 r11)
    (room-corridor r8 r12)
    (room-corridor r9 r5)
    (room-corridor r9 r13)
    (room-corridor r9 r12)
    (room-corridor r10 r6)
    (room-corridor r10 r7)
    (room-corridor r10 r14)
    (room-corridor r11 r7)
    (room-corridor r11 r8)
    (room-corridor r11 r14)
    (room-corridor r11 r15)
    (room-corridor r12 r9)
    (room-corridor r12 r8)
    (room-corridor r12 r16)
    (room-corridor r12 r15)
    (room-corridor r13 r9)
    (room-corridor r13 r16)
    (room-corridor r14 r10)
    (room-corridor r14 r11)
    (room-corridor r14 r17)
    (room-corridor r15 r12)
    (room-corridor r15 r11)
    (room-corridor r15 r17)
    (room-corridor r15 r18)
    (room-corridor r16 r12)
    (room-corridor r16 r13)
    (room-corridor r16 r18)
    (room-corridor r17 r14)
    (room-corridor r17 r15)
    (room-corridor r17 r19)
    (room-corridor r18 r16)
    (room-corridor r18 r15)
    (room-corridor r18 r19)
    (room-corridor r19 r18)
    (room-corridor r19 r17)

)
(:goal (and (hero-in-room player r19) (hero-alive player)))
)
