(define (problem pb1) (:domain dungeon)
(:objects
    player - hero
    m0 m1 m2 - monster
    t0 t1 t2 t3 t4 - trap
    s0 s1 - sword
    r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 - room
)

(:init
    (hero-alive player)
    (hero-in-room player r0)
    (hero-empty-handed player)
    
    (monster-in-room m0 r3)
    (not (monster-afraid player m0))
    (monster-in-room m1 r5)
    (not (monster-afraid player m1))
    (monster-in-room m2 r8)
    (not (monster-afraid player m2))

    (trap-in-room t0 r2)
    (trap-armed t0 r2)
    (not (trap-disarmed t0 r2))
    (trap-in-room t0 r4)
    (trap-armed t0 r4)
    (not (trap-disarmed t0 r4))
    (trap-in-room t0 r7)
    (trap-armed t0 r7)
    (not (trap-disarmed t0 r7))
    (trap-in-room t0 r9)
    (trap-armed t0 r9)
    (not (trap-disarmed t0 r9))
    (trap-in-room t0 r10)
    (trap-armed t0 r10)
    (not (trap-disarmed t0 r10))

    (sword-in-room s0 r1)
    (not (sword-destroyed s0))
    (not (sword-holding player s0))
    (sword-in-room s0 r6)
    (not (sword-destroyed s0))
    (not (sword-holding player s0))

    (not (room-destroyed r0))
    (not (room-destroyed r1))
    (not (room-destroyed r2))
    (not (room-destroyed r3))
    (not (room-destroyed r4))
    (not (room-destroyed r5))
    (not (room-destroyed r6))
    (not (room-destroyed r7))
    (not (room-destroyed r8))
    (not (room-destroyed r9))
    (not (room-destroyed r10))
    (not (room-destroyed r11))

    (room-cleared player r0)
    (not (room-cleared player r1))
    (not (room-cleared player r2))
    (not (room-cleared player r3))
    (not (room-cleared player r4))
    (not (room-cleared player r5))
    (not (room-cleared player r6))
    (not (room-cleared player r7))
    (not (room-cleared player r8))
    (not (room-cleared player r9))
    (not (room-cleared player r10))
    (not (room-cleared player r11))

    (room-corridor r0 r1)
    (room-corridor r0 r2)
    (room-corridor r1 r0)
    (room-corridor r1 r3)
    (room-corridor r1 r4)
    (room-corridor r2 r0)
    (room-corridor r2 r3)
    (room-corridor r2 r4)
    (room-corridor r3 r1)
    (room-corridor r3 r2)
    (room-corridor r3 r5)
    (room-corridor r3 r6)
    (room-corridor r4 r1)
    (room-corridor r4 r2)
    (room-corridor r4 r5)
    (room-corridor r4 r6)
    (room-corridor r5 r3)
    (room-corridor r5 r4)
    (room-corridor r5 r8)
    (room-corridor r5 r7)
    (room-corridor r6 r3)
    (room-corridor r6 r4)
    (room-corridor r6 r8)
    (room-corridor r6 r7)
    (room-corridor r7 r5)
    (room-corridor r7 r6)
    (room-corridor r7 r9)
    (room-corridor r7 r10)
    (room-corridor r8 r5)
    (room-corridor r8 r6)
    (room-corridor r8 r9)
    (room-corridor r8 r10)
    (room-corridor r9 r7)
    (room-corridor r9 r8)
    (room-corridor r9 r11)
    (room-corridor r10 r7)
    (room-corridor r10 r8)
    (room-corridor r10 r11)
)
(:goal (and (hero-in-room player r11) (hero-alive player)))
)
